env:
  - GO111MODULE=on
#before:
#  hooks:
#    - go mod download
builds:
  - id: anonip
    env:
      - CGO_ENABLED=0
    binary: anonip
    flags:
      - -trimpath
    ldflags: -s -w -X main.Version={{ .Version }} -X main.CommitSHA={{ .Commit }}
    goos:
      - linux
      - freebsd
      - openbsd
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
      - 386
      - arm
    goarm:
      - 6
      - 7

archives:
  - id: default
    builds:
      - anonip
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      windows: Windows
      darwin: Darwin
      386: i386
      amd64: x86_64

nfpms:
  - builds:
      - anonip
    vendor: open-dynaMIX
    homepage: "https://www.digitale-gesellschaft.ch"
    maintainer: "Fabio Ambauen <fabio@dnmx.ch>"
    description: "Anonip is a tool to anonymize IP addresses in log files."
    license: BSD 3-Clause
    formats:
      - apk
      - deb
      - rpm
    bindir: /usr/bin

brews:
  - goarm: 6
    tap:
      owner: open-dynaMIX
      name: homebrew-tap
    commit_author:
      name: "Fabio Ambauen"
      email: "fabio@dnmx.ch"
    homepage: "https://www.digitale-gesellschaft.ch"
    description: "Anonip is a tool to anonymize IP addresses in log files."
    # skip_upload: true

signs:
  - artifacts: checksum

checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
