name: Lint

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 0 * * 0'

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.32
          args: --exclude-use-default=false --enable golint
